/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPancakeV3MintCallback,
  IPancakeV3MintCallbackInterface,
} from "../../../../../../@pancakeswap/v3-core/contracts/interfaces/callback/IPancakeV3MintCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount0Owed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1Owed",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "pancakeV3MintCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPancakeV3MintCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeV3MintCallbackInterface {
    return new utils.Interface(_abi) as IPancakeV3MintCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPancakeV3MintCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPancakeV3MintCallback;
  }
}
