/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPancakeV3FlashCallback,
  IPancakeV3FlashCallbackInterface,
} from "../../../../../../@pancakeswap/v3-core/contracts/interfaces/callback/IPancakeV3FlashCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fee0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fee1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "pancakeV3FlashCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPancakeV3FlashCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeV3FlashCallbackInterface {
    return new utils.Interface(_abi) as IPancakeV3FlashCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPancakeV3FlashCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPancakeV3FlashCallback;
  }
}
