/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPancakeStableSwapDeployerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createSwapPair(address,address,address,uint256,uint256,uint256,address,address)"
      | "createSwapPair(address,address,uint256,uint256,uint256,address,address)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createSwapPair(address,address,address,uint256,uint256,uint256,address,address)",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSwapPair(address,address,uint256,uint256,uint256,address,address)",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSwapPair(address,address,address,uint256,uint256,uint256,address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSwapPair(address,address,uint256,uint256,uint256,address,address)",
    data: BytesLike
  ): Result;
}

export interface IPancakeStableSwapDeployer extends BaseContract {
  connect(runner?: ContractRunner | null): IPancakeStableSwapDeployer;
  waitForDeployment(): Promise<this>;

  interface: IPancakeStableSwapDeployerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "createSwapPair(address,address,address,uint256,uint256,uint256,address,address)": TypedContractMethod<
    [
      _tokenA: AddressLike,
      _tokenB: AddressLike,
      _tokenC: AddressLike,
      _A: BigNumberish,
      _fee: BigNumberish,
      _admin_fee: BigNumberish,
      _admin: AddressLike,
      _LP: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  "createSwapPair(address,address,uint256,uint256,uint256,address,address)": TypedContractMethod<
    [
      _tokenA: AddressLike,
      _tokenB: AddressLike,
      _A: BigNumberish,
      _fee: BigNumberish,
      _admin_fee: BigNumberish,
      _admin: AddressLike,
      _LP: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSwapPair(address,address,address,uint256,uint256,uint256,address,address)"
  ): TypedContractMethod<
    [
      _tokenA: AddressLike,
      _tokenB: AddressLike,
      _tokenC: AddressLike,
      _A: BigNumberish,
      _fee: BigNumberish,
      _admin_fee: BigNumberish,
      _admin: AddressLike,
      _LP: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSwapPair(address,address,uint256,uint256,uint256,address,address)"
  ): TypedContractMethod<
    [
      _tokenA: AddressLike,
      _tokenB: AddressLike,
      _A: BigNumberish,
      _fee: BigNumberish,
      _admin_fee: BigNumberish,
      _admin: AddressLike,
      _LP: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  filters: {};
}
