/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fee from "./fee";
export type { fee };
export type { ICommonOFT } from "./ICommonOFT";
export type { IOFTReceiverV2 } from "./IOFTReceiverV2";
export type { OFTCoreV2 } from "./OFTCoreV2";
